---
- name: Create a VM in GCP with Nested Virtualization enabled
  hosts: localhost
  tasks:

    - name: Include skared vars
      include_vars: shared_vars.yaml

    - name: Create the VM
      include_tasks: tasks/create-vm.yaml