---
- name: Create a VM in GCP with Nested Virtualization enabled
  hosts: localhost
  tasks:

    - name: Include skared vars
      include_vars: shared_vars.yaml

    - name: Create a disk mapped from RHEL8 image
      gcp_compute_disk:
        name: "{{ disk_name }}"
        licenses:
          - https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx
        size_gb: 80
        source_image: "{{ image_base }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
      register: disk

    - name: Create a VPC network
      gcp_compute_network:
        name: "{{ vpc_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        auto_create_subnetworks: true
        routing_config:
          routing_mode: GLOBAL
        service_account_file: "{{ service_account_file }}"
        state: present
      register: network

    - name: Create an IPv4 public IP Address
      gcp_compute_address:
        name: "{{ static_ip_name }}"
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
      register: address

    - name: Create the RHEL8 instance
      gcp_compute_instance:
        name: "{{ vm_name }}"
        min_cpu_platform: Intel Haswell
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        metadata:
          enable-oslogin: TRUE
          block-project-ssh-keys: FALSE
          ssh-keys: |
            kemo:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/UQ6SVJ0Jk/fDfLpecIIIfTe3+Ry+oaF8AFKAZwXJ8xMMmrPcPX1JTb4k/keVPT5liqYLb6pxO9yKUb1fLIKXQj+6OaDFaq7J8O3ad5AjpwMH97pynPtjUnltDIPbMTLOUHMZCrvF/PIn0iQ2lfl48lADD/S/tOPh34TI8fv+miuCO7Gdsk9DqT9SxIRG4oKj7ZKp/PKyWuPheRhJ0KiSeFIHR3dXSJnLiL+JkdBotB4IK78Pygwo6P6Wyl2P4gobkKhy/YuTiSImbaN0G8YMJrUu1EzYQ5QlmNqPKVuFH8te41vxmTX47N5h8vfO9c00YFC5H9mtsPMGXYRTiRkB kemo
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        tags:
          items:
            - eph-image-bakery
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Create a firewall rule for SSH
      google.cloud.gcp_compute_firewall:
        name: "{{ firewall_name }}"
        network: "{{ network }}"
        priority: 65534
        direction: INGRESS
        allowed:
        - ip_protocol: tcp
          ports:
          - '22'
        target_tags:
        - eph-image-bakery
        source_ranges:
        - "0.0.0.0/0"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=120

    #- name: Add host to groupname
    #  add_host: hostname={{ address.address }} groupname=new_instances

    - name: Show RHEL8 Instance Details
      debug:
        msg: "The RHEL8 instance is accessible at {{ address.address }}"
