---
- name: Delete the Gold Image Bakery VM in GCP
  hosts: localhost
  tasks:

    - name: Include skared vars
      include_vars: shared_vars.yaml

    - name: Delete the VM
      include_tasks: tasks/delete-vm.yaml