---
- name: Create a RHEL Gold Image for GCP, in GCP!
  hosts: localhost
  tasks:

    - name: Create the VM
      include_tasks: tasks/create-bakery-vm.yaml
      tags:
        - vm_setup

- name: Bake up an image
  hosts: bakery_instance
  become: yes
  tasks:

    - name: Configure the VM
      include_tasks: tasks/configure-bakery-vm.yaml
      tags:
        - vm_configure

    - name: Download latest RHEL Image
      include_tasks: tasks/rhsm-api.yaml
      tags:
        - rhsm_api

    - name: Bake RHEL Image and Upload to GCP
      include_tasks: tasks/bake-gold-image.yaml
      tags:
        - bake_image

- name: Create a RHEL Base Image VM to Configure into the final Gold Image
  hosts: localhost
  tasks:

    - name: Delete the Gold Smelter VM, just in case
      include_tasks: tasks/delete-gold-image-vm.yaml
      tags:
        - gold_destroy
      when: create_gold_smelter_vm_and_configure|bool

    - name: Create the Gold Smelter VM
      include_tasks: tasks/create-gold-image-vm.yaml
      tags:
        - gold_setup
      when: create_gold_smelter_vm_and_configure|bool

- name: Frost Base Image with Gold
  hosts: gold_smelter_instance
  tasks:

    - name: Configure the Gold Smelter VM
      include_tasks: tasks/configure-gold-image-vm.yaml
      tags:
        - gold_configure
      when: create_gold_smelter_vm_and_configure|bool

#- name: Finalize Gold Image Template
#  hosts: localhost
#  tasks:
#
#    - name: Shutdown Gold Smelter VM
#    - name: Convert to Template

- name: Clean up
  hosts: localhost
  tasks:

    - name: Delete the Gold Smelter VM
      include_tasks: tasks/delete-gold-image-vm.yaml
      tags:
        - gold_destroy
      when: create_gold_smelter_vm_and_configure|bool

    - name: Delete the VM
      include_tasks: tasks/delete-bakery-vm.yaml
      tags:
        - vm_destroy