---
- name: Set root password for QCOW2
  command:
    cmd: "/bin/virt-customize -a /opt/{{ imageList | json_query(imageFileName) | first }} --root-password password:{{ gold_image_root_password }}"

- name: Convert the QCOW2 to a RAW image
  command:
    cmd: "qemu-img convert -f qcow2 -O raw /opt/{{ imageList | json_query(imageFileName) | first }} /opt/disk.raw"
    creates: "/opt/disk.raw"

- name: Compress RAW Image
  command:
    cmd: "tar --format=oldgnu -Sczf disk.raw.tar.gz disk.raw"
    creates: "/opt/disk.raw.tar.gz"
    chdir: /opt

- name: Download the latest Google Cloud SDK Installer
  get_url:
    url: https://sdk.cloud.google.com
    dest: "/opt/gcloud-install.sh"

- name: Run gcloud install
  command:
    cmd: bash /opt/gcloud-install.sh --disable-prompts --install-dir=/opt
    creates: /opt/google-cloud-sdk/

- name: Copy over Google Cloud Service Account JSON file
  copy:
    src: "{{ service_account_file }}"
    dest: /opt/google-cloud-sdk/gcloud-creds.json

- name: Set up gcloud auth
  command:
    cmd: gcloud auth activate-service-account --key-file=/opt/google-cloud-sdk/gcloud-creds.json
    creates: /root/.config/gcloud/credentials.db

#- name: Upload compressed raw disk image to GCP Storage Bucket
#  google.cloud.gcp_storage_object:
#    action: upload
#    bucket: "{{ gcp_target_bucket }}"
#    src: /opt/disk.raw.tar.gz
#    dest: "disk.raw.tar.gz"
#    project: "{{ gcp_project }}"
#    auth_kind: "{{ gcp_cred_kind }}"
#    service_account_file: /opt/google-cloud-sdk/gcloud-creds.json

- name: Copy image to GCP Storage Bucket
  command:
    cmd: "/opt/google-cloud-sdk/bin/gsutil cp /opt/disk.raw.tar.gz gs://{{ gcp_target_bucket }}"

- name: Delete the previous VM Disk Image
  command:
    cmd: "gcloud compute images delete rhel-v{{ ansible_date_time.date }}-gold --quiet"
  when: destroy_vm_image_and_replace|bool
  ignore_errors: true

- name: Create the VM Disk Image
  command:
    cmd: "gcloud compute images create rhel-v{{ ansible_date_time.date }}-gold --source-uri gs://{{ gcp_target_bucket }}/disk.raw.tar.gz"

#- name: Create new VM Image
#  google.cloud.gcp_compute_image:
#    name: rhel8-gold-image
#    raw_disk:
#      source: "https://storage.googleapis.com/{{ gcp_target_bucket }}/disk.raw.tar.gz"
#      #source: "gs://{{ gcp_target_bucket }}/disk.raw.tar.gz"
#    project: "{{ gcp_project }}"
#    auth_kind: "{{ gcp_cred_kind }}"
#    service_account_file: /opt/google-cloud-sdk/gcloud-creds.json
#    state: present
#