---
- name: Delete previous snapshot
  google.cloud.gcp_compute_snapshot:
    name: "{{ gold_smelter_snapshot_name }}"
    source_disk: 
      name: "{{ gold_smelter_snapshot_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent
  ignore_errors: true

- name: create a snapshot
  google.cloud.gcp_compute_snapshot:
    name: "{{ gold_smelter_snapshot_name }}"
    source_disk: "{{ gold_smelter_disk }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present

- name: Delete the previous Gold Image VM Disk Image
  google.cloud.gcp_compute_image:
    name: "{{ rhel_gold_image_name }}"
    source_disk:
      name: "{{ rhel_gold_image_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent

- name: Create the Gold Image VM Disk Image
  google.cloud.gcp_compute_image:
    name: "{{ rhel_gold_image_name }}"
    source_snapshot:
      selfLink: "projects/{{ gcp_project }}/global/snapshots/{{ gold_smelter_snapshot_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present

- name: Delete snapshot to free resources
  google.cloud.gcp_compute_snapshot:
    name: "{{ gold_smelter_snapshot_name }}"
    source_disk: 
      name: "{{ gold_smelter_snapshot_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: absent
  ignore_errors: true