---

- name: Create a disk mapped from our RHEL8 Base Image
  gcp_compute_disk:
    name: "{{ gold_smelter_disk_name }}"
    size_gb: "{{ vm_disk_size }}"
    source_image: "projects/{{ gcp_project }}/global/images/{{ rhel_base_image_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present
  register: gold_smelter_disk

- name: Create an IPv4 public IP Address
  gcp_compute_address:
    name: "{{ gold_smelter_static_ip_name }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present
  register: gold_smelter_address

- name: Create the RHEL8 instance
  gcp_compute_instance:
    name: "{{ gold_smelter_vm_name }}"
    min_cpu_platform: Intel Haswell
    machine_type: "{{ gold_smelter_vm_size }}"
    disks:
    - auto_delete: 'false'
      boot: 'true'
      source: "{{ gold_smelter_disk }}"
    network_interfaces:
    - network: "{{ network }}"
      subnetwork: "{{ subnetwork }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ gold_smelter_address }}"
        type: ONE_TO_ONE_NAT
    tags:
      items:
        - eph-image-bakery
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present

# Have a delay of at least 30s - need to wait for the Login service to start
- name: Wait for SSH to come up
  wait_for: host={{ gold_smelter_address.address }} port=22 delay=30 timeout=120
  tags:
    - wait_for_gold_ssh

- name: Add host to gold_smelter_instance
  add_host:
    hostname: "{{ gold_smelter_address.address }}"
    groupname: gold_smelter_instance
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ temporary_path }}/id_rsa"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no

- name: Delete the entry from known_hosts for good measure
  command: "ssh-keygen -f ~/.ssh/known_hosts -R '{{ gold_smelter_address.address }}'"
  ignore_errors: true

- name: Show RHEL8 Gold Smelter Instance Details
  debug:
    msg: "The RHEL8 Gold Smelter instance is accessible at {{ address.address }}"
