---

- name: Log into RH SSO API
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    body_format: form-urlencoded
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rhsm_api_offline_token }}"
  register: rh_sso_reg
      
- name: Get list of images in Content Set for RHEL 8
  uri:
    url: https://api.access.redhat.com/management/v1/images/cset/rhel-8-for-x86_64-baseos-isos
    status_code: 200
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  register: content_set_image_list
  until: content_set_image_list.status == 200
  retries: 10
  delay: 10
  ignore_errors: true

- name: Set facts for filenames and download link
  set_fact:
    imageList: "{{ content_set_image_list.json.body }}"
    imageLink: >-
      [?imageName=='Red Hat Enterprise Linux 8.3 Update KVM Guest Image'].downloadHref
    imageFileName: >-
      [?imageName=='Red Hat Enterprise Linux 8.3 Update KVM Guest Image'].filename

- name: Download the latest RHEL 8 KVM Guest Image
  get_url:
    url: "{{ imageList | json_query(imageLink) | first }}"
    dest: "/opt/{{ imageList | json_query(imageFileName) | first }}"
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
